import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./_shared/components/organisms/header"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Header />
          <main className="md:py-[60px] py-[30px] bg-gradient-animation">
            <div className="c-container">
              {children}
            </div>
          </main>
        

        </div>
      </body>
    </html>
  );
}
